apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: sampleapp
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: dirghayudave/datastore:datastorev1.0.2
